# Generated by Django 4.1 on 2022-08-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Модель машины')),
                ('Power', models.IntegerField(verbose_name='Мощость')),
                ('Volume', models.FloatField(verbose_name='Объем двигателя')),
            ],
        ),
    ]
