# Generated by Django 4.1 on 2022-08-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0002_carmodel_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='DayPrice',
            field=models.IntegerField(default=100, verbose_name='Цена за сутки'),
            preserve_default=False,
        ),
    ]
