# Generated by Django 4.1 on 2022-08-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0003_alter_carmodel_options_carmodel_dayprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('CarName', models.CharField(max_length=50, verbose_name='Название машины')),
                ('Data', models.DateField(verbose_name='Дата аренды')),
            ],
        ),
    ]
