# Generated by Django 4.1 on 2022-08-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0004_rentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentmodel',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='rentmodel',
            name='mail',
            field=models.CharField(default=1, max_length=50, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
