# Generated by Django 4.1 on 2022-08-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcarsapp', '0005_alter_rentmodel_options_rentmodel_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='rentmodel',
            name='CarName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentcarsapp.carmodel'),
        ),
    ]
